/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum1;

/**
 *
 * @author ASUS
 */
public class RadioButton extends javax.swing.JPanel {

    /**
     * Creates new form RadioButton
     */
    public RadioButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        radLaki = new javax.swing.JRadioButton();
        buttonGroup1.add(radLaki);
        radPer = new javax.swing.JRadioButton();
        buttonGroup1.add(radPer);
        lblHasil = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();

        radLaki.setText("Laki");
        radLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radLakiActionPerformed(evt);
            }
        });

        radPer.setText("Perempuan");
        radPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPerActionPerformed(evt);
            }
        });

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProses)
                    .addComponent(lblHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radPer)
                    .addComponent(radLaki))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(radLaki)
                .addGap(18, 18, 18)
                .addComponent(radPer)
                .addGap(28, 28, 28)
                .addComponent(btnProses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(lblHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radLakiActionPerformed

    private void radPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radPerActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        String pil;
        if(radLaki.isSelected()) {
            pil = "Laki-laki";
        }
        else {
            pil = "Perempuan";
        }
        lblHasil.setText(pil);
    }//GEN-LAST:event_btnProsesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JRadioButton radLaki;
    private javax.swing.JRadioButton radPer;
    // End of variables declaration//GEN-END:variables
}
